package com.cskit.utils.tokens;

import java.util.Date;
import java.util.List;

public class SysAccountPO {
  
    /**
     * 店铺id列表
     */
    private List<Long> storeIdList;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.sys_account_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private Long sysAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.sys_company_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private Long sysCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.company_code
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private String companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.brand_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private Long brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.account_code
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private String accountCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.hash_password
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private String hashPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.country_code
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private String countryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.phone_number
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.name
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.position
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.status
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.reset_password
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private Boolean resetPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.last_login_date
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private Date lastLoginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.remark
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.create_user_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private Long createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.create_user_name
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.create_date
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.modified_user_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private Long modifiedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.modified_user_name
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private String modifiedUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.modified_date
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.valid
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private Boolean valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_account.ctrl_account_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    private Long ctrlAccountId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.sys_account_id
     *
     * @return the value of t_sys_account.sys_account_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public Long getSysAccountId() {
        return sysAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.sys_account_id
     *
     * @param sysAccountId the value for t_sys_account.sys_account_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setSysAccountId(Long sysAccountId) {
        this.sysAccountId = sysAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.sys_company_id
     *
     * @return the value of t_sys_account.sys_company_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public Long getSysCompanyId() {
        return sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.sys_company_id
     *
     * @param sysCompanyId the value for t_sys_account.sys_company_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setSysCompanyId(Long sysCompanyId) {
        this.sysCompanyId = sysCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.company_code
     *
     * @return the value of t_sys_account.company_code
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.company_code
     *
     * @param companyCode the value for t_sys_account.company_code
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.brand_id
     *
     * @return the value of t_sys_account.brand_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.brand_id
     *
     * @param brandId the value for t_sys_account.brand_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.account_code
     *
     * @return the value of t_sys_account.account_code
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.account_code
     *
     * @param accountCode the value for t_sys_account.account_code
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.hash_password
     *
     * @return the value of t_sys_account.hash_password
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public String getHashPassword() {
        return hashPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.hash_password
     *
     * @param hashPassword the value for t_sys_account.hash_password
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setHashPassword(String hashPassword) {
        this.hashPassword = hashPassword == null ? null : hashPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.country_code
     *
     * @return the value of t_sys_account.country_code
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.country_code
     *
     * @param countryCode the value for t_sys_account.country_code
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.phone_number
     *
     * @return the value of t_sys_account.phone_number
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.phone_number
     *
     * @param phoneNumber the value for t_sys_account.phone_number
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.name
     *
     * @return the value of t_sys_account.name
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.name
     *
     * @param name the value for t_sys_account.name
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.position
     *
     * @return the value of t_sys_account.position
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.position
     *
     * @param position the value for t_sys_account.position
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.status
     *
     * @return the value of t_sys_account.status
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.status
     *
     * @param status the value for t_sys_account.status
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.reset_password
     *
     * @return the value of t_sys_account.reset_password
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public Boolean getResetPassword() {
        return resetPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.reset_password
     *
     * @param resetPassword the value for t_sys_account.reset_password
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setResetPassword(Boolean resetPassword) {
        this.resetPassword = resetPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.last_login_date
     *
     * @return the value of t_sys_account.last_login_date
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.last_login_date
     *
     * @param lastLoginDate the value for t_sys_account.last_login_date
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.remark
     *
     * @return the value of t_sys_account.remark
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.remark
     *
     * @param remark the value for t_sys_account.remark
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.create_user_id
     *
     * @return the value of t_sys_account.create_user_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.create_user_id
     *
     * @param createUserId the value for t_sys_account.create_user_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.create_user_name
     *
     * @return the value of t_sys_account.create_user_name
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.create_user_name
     *
     * @param createUserName the value for t_sys_account.create_user_name
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.create_date
     *
     * @return the value of t_sys_account.create_date
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.create_date
     *
     * @param createDate the value for t_sys_account.create_date
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.modified_user_id
     *
     * @return the value of t_sys_account.modified_user_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public Long getModifiedUserId() {
        return modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.modified_user_id
     *
     * @param modifiedUserId the value for t_sys_account.modified_user_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setModifiedUserId(Long modifiedUserId) {
        this.modifiedUserId = modifiedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.modified_user_name
     *
     * @return the value of t_sys_account.modified_user_name
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public String getModifiedUserName() {
        return modifiedUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.modified_user_name
     *
     * @param modifiedUserName the value for t_sys_account.modified_user_name
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setModifiedUserName(String modifiedUserName) {
        this.modifiedUserName = modifiedUserName == null ? null : modifiedUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.modified_date
     *
     * @return the value of t_sys_account.modified_date
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.modified_date
     *
     * @param modifiedDate the value for t_sys_account.modified_date
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.valid
     *
     * @return the value of t_sys_account.valid
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.valid
     *
     * @param valid the value for t_sys_account.valid
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_account.ctrl_account_id
     *
     * @return the value of t_sys_account.ctrl_account_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public Long getCtrlAccountId() {
        return ctrlAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_account.ctrl_account_id
     *
     * @param ctrlAccountId the value for t_sys_account.ctrl_account_id
     *
     * @mbg.generated Fri Jul 27 19:20:23 CST 2018
     */
    public void setCtrlAccountId(Long ctrlAccountId) {
        this.ctrlAccountId = ctrlAccountId;
    }

    public List<Long> getStoreIdList() {
      return storeIdList;
    }

    public void setStoreIdList(List<Long> storeIdList) {
      this.storeIdList = storeIdList;
    }
    
    
}